site_name: Masto Guide
repo_url: https://github.com/jippi/masto-guide
edit_uri: blob/main/docs/
site_description: "MastoGuides goal is to help everyone learn about Mastodon"
site_author: "Jippi"
site_url: https://guide.toot.as/

plugins:
  - social
  - search
  - macros

extra_css:
  - css/default.css

extra_javascript:
  - js/migrate.js

markdown_extensions:
  - tables
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

theme:
  name: material
  logo: logo.png
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.share

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 📚 Mastodon guide:
      - guide/choosing-a-server.md
      - guide/getting-started-on-mastodon.md
      - guide/changing-server.md
      - guide/twitter-and-mastodon.md
      - guide/tips.md
      - guide/faq.md
  - 🇩🇰 Dansk Mastodon:
      - Hashtags: dk/hashtags.md
      - Servere: dk/servers.md
