---
categories:
  open:
    name: Åbne servere
    description: Servere du kan blive medlem af med det samme, uden godkendelse.

  review:
    name: Kræver godkendelse
    description: Servere der godkender dit medlemsskab manuelt.

  invite:
    name: Invitation påkrævet
    description: Servere der ikke accepterer nye medlemmer uden invitation.

  private:
    name: Forening / private
    description: Servere der kræver medlemsskab af en forening eller andet gruppe for at få en bruger.

servers:
  - url: https://norrebro.space
  - url: https://turingfesten.dk
  - url: https://mstdn.dk
  - url: https://helvede.net
  - url: https://expressional.social
    covenant: true
  - url: https://uddannelse.social
  - url: https://social.data.coop
    category: private
